name = "WAdag"
uuid = "ac99efd2-5092-466e-8578-e8c2155ff3fa"
authors = ["MetalFanatic"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
